public Class A000
//HelloAR
{
public Account createAccount(String name)  //method to create account
{
Account sai231111= new Account();
//org to org changes
//build with package
//whfuhfuerfhdnlkmsadhfuej
sai231111.Name = name;
return sai231111;
//autodraft changes 
//dsdsd1234111
//vbcbvcbgdfgdfdgfgfgfg
//upodarevcxvxcbcbcbcnvvbnvbnbmbmb
//new1233asfdfdsfdsgfdgvxcvxcv
//new11111111jhgjfdsfsf
//fsdfSaisource1shammmNov11saisailloydsbankklkkl
//shamshh
//jkkfds fbjhdbfhsjdfhdsfbhdsbfdfdsgyfgsjdhbfhsdbhfbds
}
}